services:
  ddg-seach-api:
    image: rohnsha0/ddg-search-api:latest
    container_name: ddg-seach-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - fastapi_network
    # Add shared memory size for Chrome (prevents crashes)
    shm_size: '2gb'

networks:
  fastapi_network:
    driver: bridge